{{- if .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "mongodb-operator.fullname" . }}
  labels:
    {{- include "mongodb-operator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ include "mongodb-operator.fullname" . }}-svc
  endpoints:
    - port: prometheus
      interval: {{ .Values.monitoring.serviceMonitor.interval }}
{{- end }}
