apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-connect.fullname" . }}
  labels:
    {{- include "kafka-connect.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: rest
      protocol: TCP
      name: rest
    {{- if .Values.jmxExporter.enabled }}
    - port: {{ .Values.jmxExporter.port }}
      targetPort: jmx-metrics
      protocol: TCP
      name: jmx-metrics
    {{- end }}
  selector:
    {{- include "kafka-connect.selectorLabels" . | nindent 4 }}
