apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "flink-jobs.fullname" . }}-log4j
  labels:
    {{- include "flink-jobs.labels" . | nindent 4 }}
data:
  log4j-console.properties: |
    rootLogger.level = {{ .Values.logging.rootLoggerLevel }}
    rootLogger.appenderRef.console.ref = ConsoleAppender
    appender.console.name = ConsoleAppender
    appender.console.type = CONSOLE
    appender.console.layout.type = PatternLayout
    appender.console.layout.pattern = {{ .Values.logging.log4jConsolePattern }}
    logger.akka.name = akka
    logger.akka.level = INFO
    logger.kafka.name = org.apache.kafka
    logger.kafka.level = WARN
    logger.hadoop.name = org.apache.hadoop
    logger.hadoop.level = WARN
    logger.zookeeper.name = org.apache.zookeeper
    logger.zookeeper.level = WARN
    {{- range $name, $level := .Values.logging.extraLoggers }}
    logger.{{ $name | replace "." "_" }}.name = {{ $name }}
    logger.{{ $name | replace "." "_" }}.level = {{ $level }}
    {{- end }}
