{{- if .Values.denyAllEgress.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "network-policies.fullname" . }}-deny-all-egress
  labels:
    {{- include "network-policies.labels" . | nindent 4 }}
spec:
  podSelector: {}
  policyTypes:
    - Egress
{{- end }}
