{{- if .Values.sidecar.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: {{ include "istio-routing.fullname" . }}
  labels:
    {{- include "istio-routing.labels" . | nindent 4 }}
spec:
  egress:
    {{- range .Values.sidecar.egress }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
    {{- end }}
{{- end }}
