{{- if .Values.secrets.csi.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "microservice.fullname" . }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
spec:
  provider: {{ .Values.secrets.csi.provider }}
  parameters:
    {{- if eq .Values.secrets.csi.provider "aws" }}
    objects: |
      {{- range .Values.secrets.csi.aws.keys }}
      - objectName: {{ .objectName | quote }}
        objectType: secretsmanager
        {{- if $.Values.secrets.csi.aws.secretArn }}
        objectAlias: {{ .objectAlias | quote }}
        {{- end }}
        {{- if .jmesPath }}
        jmesPath:
          {{- range .jmesPath }}
          - path: {{ .path | quote }}
            objectAlias: {{ .objectAlias | quote }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- else if eq .Values.secrets.csi.provider "azure" }}
    usePodIdentity: "false"
    keyvaultName: {{ .Values.secrets.csi.azure.keyvaultName | quote }}
    tenantId: {{ .Values.secrets.csi.azure.tenantId | quote }}
    objects: |
      array:
        {{- range .Values.secrets.csi.azure.objects }}
        - |
          objectName: {{ .objectName }}
          objectType: {{ .objectType }}
          {{- if .objectVersion }}
          objectVersion: {{ .objectVersion }}
          {{- end }}
        {{- end }}
    {{- else if eq .Values.secrets.csi.provider "gcp" }}
    secrets: |
      {{- range .Values.secrets.csi.gcp.secrets }}
      - resourceName: {{ .resourceName | quote }}
        fileName: {{ .objectName | quote }}
      {{- end }}
    {{- else if eq .Values.secrets.csi.provider "vault" }}
    vaultAddress: {{ .Values.secrets.csi.vault.address | default "" | quote }}
    roleName: {{ .Values.secrets.csi.vault.roleName | quote }}
    objects: |
      {{- range .Values.secrets.csi.vault.keys }}
      - objectName: {{ .objectName | quote }}
        secretPath: {{ .secretPath | quote }}
        secretKey: {{ .secretKey | quote }}
      {{- end }}
    {{- end }}
  {{- if .Values.secrets.csi.syncAsKubernetesSecret.enabled }}
  secretObjects:
    - secretName: {{ .Values.secrets.csi.syncAsKubernetesSecret.secretName }}
      type: {{ .Values.secrets.csi.syncAsKubernetesSecret.type | default "Opaque" }}
      data:
        {{- range .Values.secrets.csi.syncAsKubernetesSecret.data }}
        - objectName: {{ .objectName }}
          key: {{ .key }}
        {{- end }}
  {{- end }}
{{- end }}
