apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "secrets-csi.fullname" . }}
  labels:
    {{- include "secrets-csi.labels" . | nindent 4 }}
spec:
  provider: {{ .Values.provider }}
  parameters:
    {{- if eq .Values.provider "aws" }}
    objects: |
      {{- range .Values.aws.secrets }}
      - objectName: {{ .name | quote }}
        objectType: secretsmanager
        {{- if .secretArn }}
        objectAlias: {{ .name | quote }}
        {{- end }}
        {{- range .keys }}
        {{- if .jmesPath }}
        jmesPath:
          {{- range .jmesPath }}
          - path: {{ .path | quote }}
            objectAlias: {{ .objectAlias | quote }}
          {{- end }}
        {{- end }}
        {{- end }}
      {{- end }}
    {{- else if eq .Values.provider "azure" }}
    usePodIdentity: {{ .Values.azure.usePodIdentity | quote }}
    {{- if .Values.azure.useVMManagedIdentity }}
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.azure.userAssignedIdentityID | quote }}
    {{- end }}
    keyvaultName: {{ .Values.azure.keyvaultName | quote }}
    tenantId: {{ .Values.azure.tenantId | quote }}
    objects: |
      array:
        {{- range .Values.azure.secrets }}
        - |
          objectName: {{ .objectName }}
          objectType: {{ .objectType }}
          {{- if .objectVersion }}
          objectVersion: {{ .objectVersion }}
          {{- end }}
        {{- end }}
    {{- else if eq .Values.provider "gcp" }}
    secrets: |
      {{- range .Values.gcp.secrets }}
      - resourceName: {{ .resourceName | quote }}
        fileName: {{ .objectName | quote }}
      {{- end }}
    {{- else if eq .Values.provider "vault" }}
    {{- if .Values.vault.address }}
    vaultAddress: {{ .Values.vault.address | quote }}
    {{- end }}
    {{- if .Values.vault.namespace }}
    vaultNamespace: {{ .Values.vault.namespace | quote }}
    {{- end }}
    roleName: {{ .Values.vault.roleName | quote }}
    objects: |
      {{- range .Values.vault.secrets }}
      - objectName: {{ .objectName | quote }}
        secretPath: {{ .secretPath | quote }}
        secretKey: {{ .secretKey | quote }}
      {{- end }}
    {{- end }}
  {{- $sync := index .Values (printf "%s" .Values.provider) }}
  {{- if and $sync $sync.syncAsKubernetesSecret $sync.syncAsKubernetesSecret.enabled }}
  secretObjects:
    - secretName: {{ $sync.syncAsKubernetesSecret.secretName }}
      type: {{ $sync.syncAsKubernetesSecret.type | default "Opaque" }}
      data:
        {{- range $sync.syncAsKubernetesSecret.data }}
        - objectName: {{ .objectName }}
          key: {{ .key }}
        {{- end }}
  {{- end }}
